name: Test on FreeBSD

on: [push, pull_request]

jobs:
  testfreebsd:
    runs-on: macos-latest
    name: A job to run tests in FreeBSD
    env:
      ASSUME_ALWAYS_YES: yes
    steps:
    - uses: actions/checkout@v2
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0.1.0
      with:
        usesh: true
        prepare: pkg install -y openssl
        run: |
          # Download tyil's binary
          wget https://dist.tyil.nl/tmp/rakudo-star-amd64-fbsd-23807a36a0815ff979e58bf7faeac5fb8dfdd0f5.tar.gz -O /tmp/rakudostar.tgz
          cd /usr/
          tar xvfz /tmp/rakudostar.tgz
          cd $GITHUB_WORKSPACE
          zef install --deps-only .
          zef test . --verbose
