name: Test on FreeBSD

on: [push, pull_request]

jobs:
  testfreebsd:
    runs-on: macos-latest
    name: A job to run tests in FreeBSD
    env:
      ASSUME_ALWAYS_YES: yes
    steps:
    - uses: actions/checkout@v2
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0.1.0
      with:
        usesh: true
        prepare: pkg install -y gcc gmake openssl curl perl5 git
        run: |
          git clone https://github.com/rakudo/rakudo.git
          cd rakudo
          perl Configure.pl --backend=moar --gen-moar
          make install
          echo "export PATH=$(pwd)/install/bin:$(pwd)/install/share/perl6/site/bin:\$PATH" >> ~/.profile
          . ~/.profile
          cd /tmp/ && git clone https://github.com/ugexe/zef.git && cd zef && raku -Ilib bin/zef install .
          # Actually test
          cd $GITHUB_WORKSPACE
          zef install --deps-only .
          zef test . --verbose
